### ISSUE TITLE
error on empty search

### ISSUE THREAD

**Issue by tisdall** [braintree/braintree_python#100]
```
>>> import braintree
>>> braintree.Transaction.search()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/braintree/transaction.py", line 384, in search
    return Configuration.gateway().transaction.search(*query)
  File "/usr/local/lib/python2.7/site-packages/braintree/transaction_gateway.py", line 81, in search
    if isinstance(query[0], list):
IndexError: tuple index out of range
>>> 
```

[`if isinstance(query[0], list):`](https://github.com/braintree/braintree_python/blob/282079f09943b0d8cb63e39e7db73b136982ff07/braintree/transaction_gateway.py#L81)

needs to be changed to:  `if query and isinstance(query[0], list):`

Empty search is allowed, but requires getting around this bug by running `braintree.Transaction.search([])` which shouldn't be necessary.

**Comment by Epreuve** [comment]
Thanks for the request. We'll consider it for a future release.

Please note, that the search feature is not intended to be used as a way to fetch all records of a resource.  It is expected that a search request will have search criteria.  There is a limit on the [amount of records returned](https://developers.braintreepayments.com/reference/general/searching/search-results/python#search-limit) which also lessens this workaround's usefulness long term.

If you are looking to fetch all of a resource, please contact Braintree Support for assistance.  They should be able to help find a solution.
