### ISSUE TITLE
Pagination on `transactions/advanced_search_ids` endpoint.

### ISSUE THREAD

**Issue by luanfonceca** [braintree/braintree_python#101]
### General information

* SDK/Library version: 3.46.0
* Environment: Sandbox
* Language, language version, and OS: Python 3.6.1

### Issue description

It should be nice if the [`TransactionGateway.search`](https://github.com/braintree/braintree_python/blob/master/braintree/transaction_gateway.py#L84) method to return a `PaginatedCollection` and `PaginatedResult` as the [`DisputeGateway`](https://github.com/braintree/braintree_python/blob/master/braintree/dispute_gateway.py#L142) does.
I did:
```py
response = self.config.http().post(
    self.config.base_merchant_path() + "/transactions/advanced_search_ids?page=1&page_size=10",
    {"search": self.__criteria(query)}
)
```

But that didn't worked, i still were receiving:
```py
{'search_results': {'page_size': 50, 'ids': [... 68 items ...]}}
```

**Comment by crookedneighbor** [comment]
The transaction search API is older than the disputes API, and by default you can't adjust the page size. There is a little customization you can do, [contact our support team for details](https://articles.braintreepayments.com/forms/contact).
