### ISSUE TITLE
Support Python 3.6 and 3.7

### ISSUE THREAD

**Issue by sybrenstuvel** [braintree/braintree_python#103]
### General information

* SDK/Library version: current master (591f322b5bbc)
* Environment: n/a
* Language, language version, and OS: Python 3.6/3.7 on any OS

### Issue description

According to the `README.md` and `setup.py` files, the latest supported version of Python 3.5. Version 3.6 was released almost two years ago. Please test & support with the latest official release.

**Comment by crookedneighbor** [comment]
Thanks for mentioning this, we'll get it fixed up.

**Comment by oYukiLiu** [comment]
Does it support Python 3.6 and 3.7 now?

**Comment by crookedneighbor** [comment]
It does. We just updated our internal testing infrastructure to explicitly test against python 3.7.

The README will be updated in the next release.

**Comment by crookedneighbor** [comment]
The README has been updated https://github.com/braintree/braintree_python#dependencies

**Comment by Achilles718611** [comment]
I have got error when generate client token.

urllib3.contrib.appengine.AppEnginePlatformError: URLFetch is not available in this environment.

How to fix it?

**Comment by leeclemens** [comment]
@Achilles718611 It may be best to create a new Issue, and provide the output of `pip list` to see what versions of any other dependencies you are using.

**Comment by wodCZ** [comment]
Hello,
the [Get Started documentation for Python SDK](https://developers.braintreepayments.com/start/hello-server/python) is still outdated:

> Supports Python 2.6, 2.7, 3.3, 3.4, and 3.5.
The final version that supports Python 2.5 is 2.29.1

**Comment by crookedneighbor** [comment]
I've reported your feedback to our docs team. In the future, you can contact them directly by using the feedback button at the bottom of every docs page.
