### ISSUE TITLE
Feature Request: Ability to Log API Request & Response

### ISSUE THREAD

**Issue by npinchot** [braintree/braintree_python#106]
### General information

* SDK/Library version: 3.48.0
* Environment: All
* Language, language version, and OS: Python 2.7.15 on Ubuntu 16.04.5 LTS

### Issue description

I would like to be able to easily get a log or representation of the request and response that was sent & received for the API call. This is helpful in case we did not handle a request or response properly we can debug.

**Comment by jackellenberger** [comment]
Hi @npinchot, if all you want to do is save off the raw request and response body, you can do so by saving `request_body` and `response_body` within the [http class](https://github.com/braintree/braintree_python/blob/master/braintree/util/http.py#L78).

We don't currently have a formal logger implementation a la the [ruby sdk](https://github.com/braintree/braintree_ruby/blob/b7b2bbbbad4788886a6f5b48f858112416c8d37d/lib/braintree/configuration.rb#L99), but we could think about adding one if there is a general need for one.

I'm curious as to what you mean by debugging an improper request or response - I would think the [error result](https://developers.braintreepayments.com/reference/general/result-objects/python#error-results) pattern would give you most if not all the information you need from a failed request to both log the failure and take steps to resolve it, but I don't know your use case. Can you share any details about what situation you're planning for with this request?

**Comment by hollabaq86** [comment]
Hi @npinchot I'm going to close this but we can reopen it if you would like to provide us with more info regarding your use case.
