### ISSUE TITLE
Recommended approach to unit/integration-tests for APIs wrapping this library

### ISSUE THREAD

**Issue by somada141** [braintree/braintree_python#107]
### General information

* SDK/Library version: 3.49.0
* Environment: Sandbox
* Language, language version, and OS: Python 3.6 on Ubuntu 16.04

### Issue description

To my understanding Braintree essentially requires developers to develop a wrapper API around this library for use with a given app (I'm working on an Angular 6 app with Python backend APIs) in order to create/retrieve customers, generate tokens, create transactions/subscriptions etc.

Given that I was wondering what your recommended approach to testing said API is (referring primarily to unit-tests and integration-tests). 
- Per your example (https://github.com/braintree/braintree_flask_example) you seem to opt for mocking which fares well in unit-tests but not integration testing.
- Your recommendation for https://github.com/venmo/btnamespace in the README is nice but to my understanding the library depends on monkey-patching and wouldn't allow for changes in the deployed version of Braintree to break the tests. What's more this library is rather limited in that they only patch a small number of the gateway methods.
- My approach thus far has been to use a testing-specific sandbox which, however, makes testing fairly slow due to the round-trips and, as its not possible to programmatically purge a sandbox, ends up contaminated causing subsequent tests to fail.

I've noticed that this library is tested via a `development` environment against a server that's supposed to be running on `localhost:3000`. Is there any chance for that development variant of Braintree to be released in order to allow for integration testing without depending on mocks or actual sandboxes? Even having a closed-source binary that'd integrate with this library would be very useful.

Thanks a lot!

**Comment by hollabaq86** [comment]
Hey @somada141, we can't expose a development version of the Braintree environment. 

For unit testing we recommend mocking as you mentioned. When integration testing, you can clean up any customers or payment methods that were created from your test by deleting them from your Braintree sandbox account upon completion. 

Please note, subscriptions can be canceled but not deleted, and transactions cannot be deleted. So if you have any logic that relies on the number of transactions/subscriptions using the search methods, I'd recommend scoping the search with a timestamp to limit them to the resources created by the tests.

If you have any additional questions, feel free to contact [Braintree Support](https://developers.braintreepayments.com/forms/contact). This repo is for bugs regarding the python SDK and our Support team is better equipped to answer your integration testing questions.

**Comment by somada141** [comment]
Thanks for the tips @hollabaq86. Appreciate it :)
