### ISSUE TITLE
correct service for generating 'transaction_level_fee_reports'

### ISSUE THREAD

**Issue by xudongstadium** [braintree/braintree_python#108]
### General information

* SDK/Library version: most recent version
* Environment: Production 
* Language, language version, and OS:  Windows Python 3.7

### Issue description
After reading the sample code on https://developers.braintreepayments.com/guides/reports/custom/python
I parsed my first transaction response, but it is actually the report under 'Transaction Search', which has no info regarding the transaction fee; 

I know the sample use service 'gateway.transaction.search', so of course will generate 'Transaction Search',  Could anybody give me the hint of which service I should use to generate  'transaction_level_fee_reports'? which contains these info:
(Discount Credit | Per Transaction Fee | Per Transaction Fee Credit | Braintree Total Amount | Multicurrency Fee Amount | Multicurrency Fee Credit | Total Fee   Amount)

Thanks in advance

**Comment by crookedneighbor** [comment]
That product is in beta, and it'd be best to reach out to our support team for assistance with it. https://help.braintreepayments.com/
