### ISSUE TITLE
'BraintreeGateway' object has no attribute 'report'

### ISSUE THREAD

**Issue by dmitriyshashkin** [braintree/braintree_python#115]
### General information

* SDK/Library version: 3.57.1
* Environment: Production
* Language, language version, and OS: Python 3.7.0 on Fedora 29

### Issue description

I tried to access the report using the documentation here.
https://developers.braintreepayments.com/reference/request/report/transaction-level-fees/python

Got the following error: `AttributeError: 'BraintreeGateway' object has no attribute 'report'`

**Comment by hollabaq86** [comment]
👋 @dmitriyshashkin, thanks for reaching out. I apologize that our docs are inaccurate, this feature is only available in the Java SDK or via [GraphQL API](https://graphql.braintreepayments.com/). 

I'm going to forward this along to our Docs team to remove this page, but in the meantime, you can use GraphQL to retrieve [this information](https://graphql.braintreepayments.com/reference/#object--transactiondescriptor) programmatically.

**Comment by m-wainwright-samaritans** [comment]
Hi @hollabaq86 , this documentation is showing Transaction Level Fees but the attribute is still missing, has the functionality been added yet?

https://developer.paypal.com/braintree/docs/reference/request/report/transaction-level-fees/python

**Comment by hollabaq86** [comment]
👋 @m-wainwright-samaritans i don’t work at Braintree anymore, i recommend creating a new issue referencing this old one so that whoever is working there can take a look. Sorry!
