### ISSUE TITLE
Braintree ID's Length

### ISSUE THREAD

**Issue by UmairShahzad** [braintree/braintree_python#116]
### General information

* SDK/Library version: 3.20.0
* Environment: Sandbox & Production
* Language, language version, and OS: Python 2.7 on Mac OS
### Issue description

The Docs suggest that the subscription ID can consist of 36 characters max, however, the API or Braintree do not impose any such limits. I can create subscriptions with IDs of length even greater than 255. Is this the desired behaviour? Will braintree restrict this future or can I rely on ID's with length > 36?

**Comment by crookedneighbor** [comment]
You should adhere to the docs about the limit.

If a hard limit is created in the future, you will be notified about any subscriptions that need to be updated, but the easiest thing to do would be to update any existing ids to adhere to the 36 character limit. https://developers.braintreepayments.com/reference/request/subscription/update/python
