### ISSUE TITLE
Issues with plan:all method and search customers

### ISSUE THREAD

**Issue by ngodichat** [braintree/braintree_python#118]
### General information

* SDK/Library version: 3.58.0
* Environment: Sandbox 
* Language, language version, and OS:  Python 3.7.3 on Windows 10

### Issue description
I have 3 issues:

1. I cannot search customers by their emails:
```py
import braintree

gateway = braintree.BraintreeGateway(access_token='access_token$sandbox$26w4mng8x8pffcnm$0af251fab25f98f1ccaff8800a77d5c2')
collection = gateway.transaction.search([
    braintree.TransactionSearch.customer_email != "abc"
])

collection = gateway.customer.search(braintree.CustomerSearch.email != "abc@gmail.com")
for customer in collection.items:
    print('first_name: ',customer)
```

The server always return `Error: braintree.exceptions.server_error.ServerError`

2. I can't get all plans by doing as written in the documentation, it always returns `braintree.exceptions.authorization_error.AuthorizationError: None` while there's no Resource-oriented OAuth scopes for this method. 
The code is as follow:
```py
import braintree

gateway = braintree.BraintreeGateway(access_token='access_token$sandbox$26w4mng8x8pffcnm$0af251fab25f98f1ccaff8800a77d5c2')
collection = gateway.plan.all()

collection = gateway.customer.search(braintree.CustomerSearch.email != "abc@gmail.com")
for plan in collection.items:
    print('first_name: ', plan)
```
3. And I can't find the customer id in the search result of transaction, what is the best way to get that information?

Thank you very much!

**Comment by scannillo** [comment]
Hello. Here are our docs links to the two errors [#1](https://developers.braintreepayments.com/reference/general/exceptions/python#server-error) and [#2](https://developers.braintreepayments.com/reference/general/exceptions/python#authorization-error) you're seeing.

In regards to question #3, here is a link to our docs for searching for [customers](https://developers.braintreepayments.com/reference/request/customer/search/python). But our Support team can take your questions on this functionality.

Please contact support at support@getbraintree.com, who can help troubleshoot your specific integration. Feel free to open a new issue if you find an issue with our SDK.

**Comment by hollabaq86** [comment]
👋 @ngodichat, please contact [Support](https://help.braintreepayments.com/) referencing this issue.  They'll partner with the team that owns OAuth to answer your questions and look into the source of the issues you're seeing with your searches.

Also for future reference, Access Tokens should not be shared in a public forum like GitHub (even sandbox tokens 😄). I went ahead and removed your access token for security.

**Comment by ngodichat** [comment]
@hollabaq86 Thank you :)
