### ISSUE TITLE
Dates are in utc?

### ISSUE THREAD

**Issue by Noushida** [braintree/braintree_python#122]
Is Settlement date  and created date of transaction search result are in utc or local?

**Comment by hollabaq86** [comment]
👋 @Noushida Our [docs](https://developers.braintreepayments.com/reference/request/transaction/search/python) state:

>Results will always be returned with time values in UTC.

Granted, this note is at the _very_ bottom of the transaction search page... We can update our docs to make this info easier to find 😄
