### ISSUE TITLE
Cannot Update CreditCard as default payment method to FALSE

### ISSUE THREAD

**Issue by TheAshwanik** [braintree/braintree_python#123]
### General information

* SDK/Library version: 
$ cat /app/.local/lib/python3.7/site-packages/braintree/version.py
Version = "4.2.0"

* Environment: Sandbox

* Language, language version, and OS:  Python 3

### Issue description

 i am able to update a credit card as default payment method for the selected customer using this code.

```
result = braintree.CreditCard.update(token,{
         "options": {
                       "make_default": True,
         },
})
```

**But I am not able to make same card as non_default . This does not work:**

```
result = braintree.CreditCard.update(token,{
         "options": {
                       "make_default": False,
         },
})
```

I have some assumption , just wanted to check.
Is it not working because there must be one creditCard set as default? and by make it false, it does not allow me?

Does it mean - make_default can only make some payment method as True and not False?

**Comment by TheAshwanik** [comment]
And It does not work with the update PaymentMethod also.
```
result = braintree.PaymentMethod.update( token, {
        "options": {
                  "make_default": False
               }
    })
```

**Comment by hollabaq86** [comment]
👋  @TheAshwanik, thanks for reaching out. You are correct - `make_default: false` has no effect, the same as if you were not including that parameter at all in your calls.

At least one payment method must be the default- if you want to make sure a payment method is _not_ the default, you have to make a different payment method the default (i.e. `pass make_default: true` on a different one).

If you have additional questions about this parameter, please [contact Support](https://help.braintreepayments.com/).

**Comment by TheAshwanik** [comment]
Thanks.. it would help if the documentation is updated to mention that true is only accepted value.
Thanks for the great work.

**Comment by crookedneighbor** [comment]
At the bottom of every docs page is a "Send Feedback" button, so if you think the documentation needs improving, that's the best way to get in contact with our documentation team. https://developers.braintreepayments.com/reference/request/payment-method/update/#feedback-link
