### ISSUE TITLE
Increase Page size

### ISSUE THREAD

**Issue by mohamedfawzy96** [braintree/braintree_python#125]
Is there a way to increase the page size of the transactions returned with batch ids using the search function ?

**Comment by hollabaq86** [comment]
👋  @mohamedfawzy96 sorry for the delay. Page size is currently set by our search API and not something that can be set externally by merchants.

That said, I forwarded your feature request to our Search team for them to review, and I'll leave this issue open to track interest.

**Comment by hollabaq86** [comment]
Also want to mention that you may want to look at the work we're doing with GraphQL as we do support paginating results with GraphQL requests.
