### ISSUE TITLE
default parameter is not part of the PaymentMethodNonce object

### ISSUE THREAD

**Issue by anu-kailash** [braintree/braintree_python#127]
### General information

* SDK/Library version: 4.4.0
* Environment: Sandbox
* Language, language version, and OS: Python 3.6 and 3.8 on Debian stretch and Ubuntu

### Issue description

https://developers.braintreepayments.com/reference/response/payment-method-nonce/python#default
The documentation describes a boolean parameter named 'default' which is not present in the nonce object returned by this SDK.
I have also raised this with Braintree Support in case this is a documentation/API issue.

```
>>> nonce = gateway.payment_method_nonce.find('fake-valid-debit-nonce')
>>> nonce.default
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'PaymentMethodNonce' object has no attribute 'default'
>>> nonce['default']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'PaymentMethodNonce' object is not subscriptable
>>> 
```

**Comment by hollabaq86** [comment]
👋  @anu-kailash thanks for reaching out. The payment method nonce needs to represent a payment method that's stored in your Vault, `default` isn't returned for payment method nonces representing single-use payment methods.

We can make our reference documentation more clear about this. I'll leave this issue open until those get updated.

**Comment by hollabaq86** [comment]
Docs are updated! Closing this issue
