### ISSUE TITLE
Braintree created subscription not showing in sandox account

### ISSUE THREAD

**Issue by Avin-Techv** [braintree/braintree_python#135]
I need to implement a subscription via debit card/ credit card via Braintree, based on the official docs I added an API call to the purchase button click which would create a subscription-like the code

```
result = gateway.subscription.create({
    "payment_method_token": "the_token",
    "plan_id": "the_plan_id"
})
```
when I check if it successful via

` result.is_success 
`
I get true, so my question is does the subscription will be created in the https://sandbox.braintreegateway.com/ as well ? is this much enough for the implementation?

I am using
Django=3.1
braintree==4.10.0

**Comment by crookedneighbor** [comment]
That should work, assuming `payment_method_token` and `plan_id` refer to actual payment methods and plans in your gateway. Please reach out to our support team for assistance with this. https://developer.paypal.com/braintree/help

**Comment by Avin-Techv** [comment]
I am not getting the subscription listed in my sandbox account, the `payment_method_token` and `plan_id`refers to actual payment methods

**Comment by crookedneighbor** [comment]
Please reach out to our support team so they can help you investigate the issue.
