### ISSUE TITLE
Headers provided by braintree http util contain mixture of str/bytes

### ISSUE THREAD

**Issue by jhance** [braintree/braintree_python#139]
In particular the authentication related headers are weirdly explicitly encoded to bytes whereas all the other headers are strings. This is unintuitive when using a custom http strategy and we need to "fix up" the headers to not contain bytes.

**Comment by hollabaq86** [comment]
👋  @jhance thanks for reaching out, and apologies for the delay in a reply. To confirm, you're referring to how we're setting [authorization](https://github.com/braintree/braintree_python/blob/59a921704edb59fdd6ff4f449d8b09ca7a9668f2/braintree/util/http.py#L151-L165) in our HTTP class?

We're encoding authentication per the [HTTP spec](https://datatracker.ietf.org/doc/html/rfc7617), but it looks like there's [a few changes](https://stackoverflow.com/q/38214765) over the different versions of python on libraries that can be used for this, and encodebytes might be a candidate for updating.

I'm not confirming that we'll change this, but I'm going to leave this open for us to keep in mind for updates in future major versions updates.

**Comment by hollabaq86** [comment]
I took a deeper look at this and I'm not seeing any changes that we should make in a next major version... I'm wary of letting authorization be custom written in any way out of the box in the SDK. This should remain something that folks who need to do so incorporate that logic themselves. Going to close this as something we won't do.
