### ISSUE TITLE
Include updated_at field in TransactionSearch

### ISSUE THREAD

**Issue by DaniilLPG** [braintree/braintree_python#145]
Similar to [this ticket](https://github.com/braintree/braintree_ruby/issues/101) (appreciate it's Ruby client), would it be possible to include `updated_at` field in [TransactionSearch](https://github.com/braintree/braintree_python/blob/master/braintree/transaction_search.py)? The use case for that is to retrieve the latest data from BrainTree, as right now I have to issue a query per timestamp field, combine transactions and deal with duplicates.

**Comment by hollabaq86** [comment]
👋 @DaniilLPG thanks for reaching out. I've gone ahead and forwarded your feedback to our product teams for consideration.

**Comment by Tacobell3669** [comment]
Would love to see this feature added. Can't really incrementally update without being able to search by `updated_at` for transactions, and that means my team ends up having to fully ingest all of our transactions with each run if we want an accurate state (this is typically a 30 hour run 🤦‍♂️)

**Comment by kgoutham** [comment]
Hello , We are encountering similar issue , Is there any workaround for this ? @Tacobell3669
