### ISSUE TITLE
braintree python sdk support initWithAuthorization/initWIthAPIClient like iOS SDK and receive client token as argues?

### ISSUE THREAD

**Issue by iamxuyu617** [braintree/braintree_python#151]
### General information

* SDK/Library version: 
* Environment: 
* Language, language version, and OS:

**Comment by hollabaq86** [comment]
The python SDK is designed for a server-side integration, and has the [generate method](https://developer.paypal.com/braintree/docs/reference/request/client-token/generate/python) for creating client tokens.

For more info, check out our [developer docs](https://developer.paypal.com/braintree/docs/start/hello-server/python). For any additional questions, [contact Support](https://developer.paypal.com/braintree/help).
