### ISSUE TITLE
HTTP POST failing with latest requests lib

### ISSUE THREAD

**Issue by acechase** [braintree/braintree_python#50]
I have recently updated the requests library in my project to version 2.6.0. Specifically, I ran "pip install --upgrade requests[security]" and the following requirements were changed:
```
< XlsxWriter==0.6.2
---
> XlsxWriter==0.6.3
17d16
< cffi==0.9.2
20d18
< cryptography==0.8
33d30
< django-sql-stacktrace==0.2.2
40d36
< enum34==1.0.4
65d60
< ndg-httpsclient==0.3.3
71,73d65
< pyOpenSSL==0.14
< pyasn1==0.1.7
< pycparser==2.10
81c73
< requests==2.6.0
---
> requests==2.4.3
87c79
< six==1.9.0
---
> six==1.8.0
```

After making that update I see the following errors occurring when attempting to communicate with braintree:
```
  File "/Users/andrew/code/EatWith/EatWith/apps/credit_cards/braintree/braintree_interaction_manager.py", line 231, in braintree_sale
    result = braintree.Transaction.sale(braintree_data)
  File "/Users/andrew/.virtualenvs/EatWith/lib/python2.7/site-packages/braintree/transaction.py", line 312, in sale
    return Transaction.create(params)
  File "/Users/andrew/.virtualenvs/EatWith/lib/python2.7/site-packages/braintree/transaction.py", line 407, in create
    return Configuration.gateway().transaction.create(params)
  File "/Users/andrew/.virtualenvs/EatWith/lib/python2.7/site-packages/braintree/transaction_gateway.py", line 33, in create
    return self._post("/transactions", {"transaction": params})
  File "/Users/andrew/.virtualenvs/EatWith/lib/python2.7/site-packages/braintree/transaction_gateway.py", line 137, in _post
    response = self.config.http().post(url, params)
  File "/Users/andrew/.virtualenvs/EatWith/lib/python2.7/site-packages/braintree/util/http.py", line 49, in post
    return self.__http_do("POST", path, params)
  File "/Users/andrew/.virtualenvs/EatWith/lib/python2.7/site-packages/braintree/util/http.py", line 71, in __http_do
    raise e
TypeError: data must be a byte string
```

I have observed this behavior both on localhost (on my macbook) running in the development environment, as well as running on the heroku cedar-14 stack (ubuntu based) in the production environment.

It seems to me that the most recent updates to the requests library have introduce an incompatibility with the braintree lib. Does this sound correct? 

Also, I see support for different http strategies in the configuration object, but I can't find documentation or examples anywhere showing how to use a different strategy. Would appreciate any pointers to references that may be available.

**Comment by agfor** [comment]
@acechase Thanks for the report; I'll test against recent versions of requests this week.

An http strategy needs to implement [two methods, `http_do` and `handle_exceptions`](https://github.com/braintree/braintree_python/blob/master/braintree/util/http.py#L81-L100). You can set it by [passing it as a keyword argument when you configure the Braintree library](https://github.com/braintree/braintree_python/blob/master/braintree/configuration.py#L18-L25).

**Comment by agfor** [comment]
@acechase We were unable to reproduce your issue. Can you provide a complete code sample that triggers the error, along with your Python, braintree_python, and dependency versions?

**Comment by kongdigital** [comment]
I had the same problem I rolled back to requests version 2.6.0 and Braintree 3.11. Fixed it right up.

Annoying as hell though

**Comment by adrienbrunet** [comment]
Same for me.

**Comment by agfor** [comment]
@kongdigital @adrienbrunet Likely the same issue as https://github.com/braintree/braintree_python/issues/53 if requests 2.6.0 works and later versions don't.
