### ISSUE TITLE
Plan not returning price as decimal

### ISSUE THREAD

**Issue by andymckay** [braintree/braintree_python#52]
```
In [12]: plans[0]      
Out[12]: <Plan {billing_day_of_month: None, trial_duration: None, description: u'A brick', billing_frequency: 1, trial_period: False, price: u'10.00', currency_iso_code: u'USD', updated_at: datetime.datetime(2015, 4, 3, 15, 10, 30), trial_duration_unit: u'day', number_of_billing_cycles: None, discounts: [], add_ons: [], created_at: datetime.datetime(2015, 4, 3, 15, 10, 30), merchant_id: u'tbb7hb44zx28jhsh', id: u'concrete-brick', name: u'Concrete'} at 62648720>

In [13]: plans[0].price
Out[13]: u'10.00'
```

Would be easier to use if it was parsed as a decimal.

**Comment by ryanjpodonnell** [comment]
Hey @andymckay,

It seems we do return Unicode while in our [documentation](https://developers.braintreepayments.com/javascript+python/reference/response/plan#price), we say we return Decimal. We will fix this in our docs.

If you need the response to be Decimal, you can easily [cast it](https://docs.python.org/2/library/unicodedata.html) to one.

Thanks for bringing this to our attention!
