### ISSUE TITLE
Webhook verify Accept Header incorrect

### ISSUE THREAD

**Issue by andymckay** [braintree/braintree_python#54]
When you set up webhook on braintree it sends a request to the server to check it can receive that request. The docs recommend getting that request, verifying and returning the response, for example:

https://developers.braintreepayments.com/javascript+python/guides/webhooks/create#bt-challenge

What they don't say is that the request from braintree will send Accept headers in the request that look like this:

[u'*/*; q=0.5', u'application/xml']

But the Braintree end of things does not accept any response or "application/xml". It only accepts one things and that is the response echoed back, no XML or JSON encoding applied. It does not accept */*. 

The request for the verify end point should send an Accept header of: text/plain.

**Comment by raymondberg** [comment]
Hi @andymckay!  We did some review and our test cases all showed that we are sending `*/*; q=0.5, application/xml`. Can you double check that the headers you're seeing exclude `*/*` seeing? You’re absolutely right that an Accept header of `*/*; q=0.5 text/plain` would seem to make more sense. We will look at updating that to be more accurate!

**Comment by andymckay** [comment]
Looks like my wiki syntax foo in the original comment was week and it was stripping the * out of the Accept strings. I just confirmed that the Accept header from Braintree on this endpoint is:  ```'*/*; q=0.5, application/xml'```

It feels like that the fix is for the request on Braintree's end to be correct, followed by this library and its tests.

**Comment by raymondberg** [comment]
We rolled this change into our environment. We have separate test cases internally to handle this case, but we're going to leave the sad path tests out of the individual client library tests. Thanks again!
