### ISSUE TITLE
Translating errors

### ISSUE THREAD

**Issue by manikos** [braintree/braintree_python#82]
Are there any plans or may I contribute somehow in order to translate (at least in my language, Greek) all the error codes (or at least most of them)?

I am asking this because I have a multilingual website and I want any potential errors produced (e.g 
`code: 81715`, `text: Credit card number is invalid`) to appear on the language selected by the user.

Maybe [transifex](https://www.transifex.com/) be used (same service used by [Django](https://www.djangoproject.com/))?

**Comment by lkorth** [comment]
@manikos

We do not currently plan on returning translated error messages from the API. The error codes exist so that you can use those to return the appropriate error message to the user in whatever language they may need it in.
