### ISSUE TITLE
Braintree modules cannot be imported

### ISSUE THREAD

**Issue by horaceleung** [braintree/braintree_python#89]
We have encountered following error after upgrading from 3.35.0 to 3.36.0 causing some modules unable to be imported.

plugins_1    |     import braintree
plugins_1    |   File "/usr/local/lib/python3.4/site-packages/braintree/_init_.py", line 1, in <module>
plugins_1    |     from braintree.ach_mandate import AchMandate
plugins_1    |   File "/usr/local/lib/python3.4/site-packages/braintree/ach_mandate.py", line 2, in <module>
plugins_1    |     from braintree.util.datetime_parser import parse_datetime
plugins_1    | ImportError: No module named 'braintree.util.datetime_parser'
plugins_1 exited with code 1

**Comment by bmdeveloppement** [comment]
+1, I have the same issue. Rollback to 2.35.0 for the moment.

**Comment by grameh** [comment]
+1 having the issue as well.
3.35.0 is the release before this and it seems to be working

**Comment by crookedneighbor** [comment]
Thanks for the report. We'll have a fix out today.

**Comment by crookedneighbor** [comment]
This is fixed in 3.37.0. Thanks for your patience!
