### ISSUE TITLE
Search subscriptions by `updated_at` field?

### ISSUE THREAD

**Issue by frnsys** [braintree/braintree_python#91]
Is there any way to search subscriptions by `updated_at`? I'm trying to query the number of cancellations given a datetime range and currently there doesn't seem to be a way to do that.

**Comment by frnsys** [comment]
I'm currently trying to search for all subscriptions with a status of Canceled, then iterate over all of them and check if `updated_at` is within the specified range. But this is very slow and I always hit a `ConnectTimeout` before I can iterate through the entire result set (of about ~2000 items).

**Comment by crookedneighbor** [comment]
According to our records, this was answered in a support ticket back in June. I'm going to go ahead and close this, but if you need further assistance, feel free to comment or open a new support ticket.
