### ISSUE TITLE
Retrieving all subscriptions and transactions

### ISSUE THREAD

**Issue by mpclarkson** [braintree/braintree_python#93]
### General information

* SDK/Library version: Current
* Environment: All
* Language, language version, and OS: Python 3.6

### Issue description

It is possible to retrieve all customers via `braintree.Customer.all()` and all plans via `braintree.Plan.all()` but the `all` method does not exist for `Transactions` or `Subscriptions`. 

How can these these be retrieved efficiently? I don't want to find or search - I need the complete lists.

Many thanks

**Comment by jaypatel512** [comment]
Hey @mpclarkson !

Unfortunately, we do not have `all` available for transactions and plans. We recommend merchants to keep track of all the transactions and subscriptions. To fetch a subset of data, you can easily use `search` with proper parameters.

**Comment by adrianforsius** [comment]
When a search reach the limit how is the data returned concatinated?

**Comment by crookedneighbor** [comment]
@adrianforsius reach out to our support team for assistance https://help.braintreepayments.com/
