### ISSUE TITLE
Search vault customer by "Custom Fields"

### ISSUE THREAD

**Issue by JosephDev** [braintree/braintree_python#97]
### General information

* SDK/Library version: 3.39.1
* Environment: Sandbox
* Language, language version, and OS: python 3.x

### Issue description
I'd like to record custom fields to map customer between BT and our own system.
is there any chance to add this feature on your system?
I know I can assign `id` but I need one more uniq field.
ex)
```
braintree.Customer.create({
	"first_name": "john",
	"last_name": "doe",
	"company": "democom",
	"email": "demo@demo.com",
	"phone": "xxx.xxx.xxxxx",
	"fax": "",
	"website": "",
	"custom_fields": {
                "own_custom_id": "123456"
	}
})
```
and search like
```
collection = braintree.Customer.search(
    braintree.CustomerSearch.custom_fields.own_custom_id == '123456'
)
```

**Comment by JosephDev** [comment]
@crookedneighbor thank you for your answer. I'd like to mark customer id to verify customer's information and authority.

**Comment by crookedneighbor** [comment]
I am not familiar with what you are referring. Can you be more specific about your use case?

**Comment by JosephDev** [comment]
According to the BT's control panel, I don't think I can search a customer or payments by custom field. I will figure another way out to map local customer or/and payments data to BrainTree.

**Comment by crookedneighbor** [comment]
You are correct. It _should_ be as simple as saving the Braintree customer id to the customer in your database.
